"""Add redline and diff columns to RiskFlag

Revision ID: 2b7629002d4e
Revises: 5ae527790701
Create Date: 2026-10-06 17:12:07.313737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7629002d4e'
down_revision: Union[str, None] = '5ae527790701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_flags', sa.Column('suggested_redline', sa.String(), nullable=True))
    op.add_column('risk_flags', sa.Column('plain_english_explanation', sa.String(), nullable=True))
    op.add_column('risk_flags', sa.Column('redline_diff', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_flags', 'redline_diff')
    op.drop_column('risk_flags', 'plain_english_explanation')
    op.drop_column('risk_flags', 'suggested_redline')
    # ### end Alembic commands ###
