"""Update vector embeddings to 768 for gemini

Revision ID: 41ad3443776f
Revises: 5f45a4fd54ed
Create Date: 2026-10-03 18:06:29.014222

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '41ad3443776f'
down_revision: Union[str, None] = '5f45a4fd54ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extracted_clauses', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.alter_column('standard_clauses', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standard_clauses', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.alter_column('extracted_clauses', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
