"""Add RiskFlag table for evidence binding

Revision ID: 5ae527790701
Revises: e86d433759d5
Create Date: 2026-10-04 21:52:55.043525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae527790701'
down_revision: Union[str, None] = 'e86d433759d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_flags', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('risk_flags', sa.Column('ai_model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_flags', 'ai_model_version')
    op.drop_column('risk_flags', 'similarity_score')
    # ### end Alembic commands ###
