"""Add RiskFlag table for evidence binding

Revision ID: e86d433759d5
Revises: 730884713c8d
Create Date: 2026-10-04 21:41:57.820614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86d433759d5'
down_revision: Union[str, None] = '730884713c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extracted_clause_id', sa.UUID(), nullable=False),
    sa.Column('standard_clause_id', sa.UUID(), nullable=True),
    sa.Column('flag_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('flag_reason', sa.String(), nullable=False),
    sa.Column('evidence_text', sa.String(), nullable=False),
    sa.Column('baseline_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_override_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extracted_clause_id'], ['extracted_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_clause_id'], ['standard_clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_extracted_clauses_embedding', table_name='extracted_clauses', postgresql_with={'m': '16', 'ef_construction': '128'}, postgresql_using='hnsw')
    op.drop_index('idx_standard_clauses_embedding', table_name='standard_clauses', postgresql_with={'m': '16', 'ef_construction': '128'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_standard_clauses_embedding', 'standard_clauses', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '128'}, postgresql_using='hnsw')
    op.create_index('idx_extracted_clauses_embedding', 'extracted_clauses', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '128'}, postgresql_using='hnsw')
    op.drop_table('risk_flags')
    # ### end Alembic commands ###
